import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";

import { eq } from "drizzle-orm";

import { hlsCaptionsPath, paths } from "@/lib/paths";
import { logger } from "@/lib/log";
import { captureException } from "@/lib/error-monitoring";
import { isWhisperAvailable, transcribe } from "@/lib/transcribe/whisper";
import { db } from "@/server/db/client";
import { videoCaptions, videos } from "@/server/db/schema/videos";
import { join } from "node:path";

const log = logger("transcribe");

export type TranscribePayload = {
    videoId: string;
    /** When true, replace any existing auto-generated track for the same lang. */
    overwrite?: boolean;
};

// pg-boss handler that runs whisper.cpp (or an external API) against a
// transcoded video and inserts a video_captions row.
export const transcribeHandler = async (jobs: Array<{ data: TranscribePayload }>): Promise<void> => {
    for (const job of jobs) {
        const { videoId, overwrite = false } = job.data;
        try {
            await runOne(videoId, overwrite);
        } catch (err) {
            log.error("transcribe failed", {
                videoId,
                err: err instanceof Error ? err.message : String(err),
            });
            captureException(err);
        }
    }
};

const runOne = async (videoId: string, overwrite: boolean): Promise<void> => {
    if (!isWhisperAvailable()) {
        log.info("skip: whisper not configured", { videoId });
        return;
    }

    const videoRows = await db.select().from(videos).where(eq(videos.id, videoId)).limit(1);
    const video = videoRows[0];
    if (!video) {
        log.warn("video not found", { videoId });
        return;
    }
    if (video.status !== "ready") {
        log.warn("video not ready", { videoId, status: video.status });
        return;
    }

    const sourcePath = join(paths.sourceRoot, video.sourcePath);
    log.info("transcribing", { videoId, sourcePath });

    const start = Date.now();
    const { vtt, detectedLang } = await transcribe(sourcePath);
    log.info("transcribe done", { videoId, detectedLang, ms: Date.now() - start });

    // Write the VTT to the same caption directory the embedded extractor uses
    // so the existing /api/hls/<id>/captions/<lang>.vtt route serves it.
    const target = hlsCaptionsPath(videoId, detectedLang);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, vtt);

    const vttRelative = relative(paths.hlsRoot, target);

    // Upsert: a manual sidecar in the same lang takes precedence unless
    // overwrite is set. We always tag isAutoGenerated=true so the UI can
    // distinguish (e.g. a small "Auto" badge in the captions menu).
    const existing = await db
        .select({ id: videoCaptions.id, isAutoGenerated: videoCaptions.isAutoGenerated })
        .from(videoCaptions)
        .where(eq(videoCaptions.videoId, videoId))
        .limit(50);

    const sameLang = existing.find((c) => c.id && (c as unknown as { lang?: string }).lang === detectedLang);
    if (sameLang) {
        if (!overwrite && !sameLang.isAutoGenerated) {
            log.info("preserving manual caption", { videoId, lang: detectedLang });
            return;
        }
        await db
            .update(videoCaptions)
            .set({
                label: "Auto",
                source: "sidecar",
                vttPath: vttRelative,
                isAutoGenerated: true,
            })
            .where(eq(videoCaptions.id, sameLang.id));
    } else {
        await db.insert(videoCaptions).values({
            videoId,
            lang: detectedLang,
            label: "Auto",
            source: "sidecar",
            vttPath: vttRelative,
            isDefault: existing.length === 0,
            isAutoGenerated: true,
        });
    }
};
