import { execFile, spawn } from "node:child_process";
import { mkdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

import { env } from "@/env";
import { logger } from "@/lib/log";

const execFileAsync = promisify(execFile);
const log = logger("whisper");

// Two transcription paths: a local whisper.cpp binary, or a Whisper-compatible
// HTTP endpoint. The worker prefers the binary when both are configured.
//
// Output is always WebVTT. The caller writes the VTT next to the video's HLS
// output and inserts a video_captions row with source='sidecar' and
// isAutoGenerated=true.

export type TranscribeResult = {
    vtt: string;
    detectedLang: string;
};

export const isWhisperAvailable = (): boolean => {
    if (env.WHISPER_BINARY_PATH && env.WHISPER_MODEL_PATH) return true;
    if (env.WHISPER_API_URL) return true;
    return false;
};

// ---------------------------------------------------------------------------
// Path A: local whisper.cpp binary
// ---------------------------------------------------------------------------

const transcribeViaBinary = async (sourcePath: string): Promise<TranscribeResult> => {
    const binary = env.WHISPER_BINARY_PATH!;
    const model = env.WHISPER_MODEL_PATH!;

    // We extract a 16 kHz mono WAV first because whisper.cpp expects PCM WAV.
    // ffmpeg is in the runner image and on most operator hosts.
    const tmpDir = await mkdir(join(tmpdir(), `cassette-whisper-${Date.now()}`), { recursive: true });
    const wavPath = join(tmpDir!, "audio.wav");
    const outPrefix = join(tmpDir!, "audio");

    try {
        log.info("extracting audio", { sourcePath, wavPath });
        await spawnSilent("ffmpeg", [
            "-y",
            "-i",
            sourcePath,
            "-ar",
            "16000",
            "-ac",
            "1",
            "-c:a",
            "pcm_s16le",
            "-vn",
            wavPath,
        ]);

        log.info("running whisper", { binary, model, input: wavPath });
        // whisper.cpp's `whisper-cli` writes <prefix>.vtt when --output-vtt is set.
        await spawnSilent(binary, [
            "-m",
            model,
            "-f",
            wavPath,
            "--output-vtt",
            "--output-file",
            outPrefix,
            "--language",
            "auto",
            "--threads",
            String(Math.max(1, Math.min(8, navigatorHardwareConcurrency()))),
        ]);

        const vtt = await readFile(`${outPrefix}.vtt`, "utf8");
        const detectedLang = inferLangFromVtt(vtt) ?? "en";

        return { vtt, detectedLang };
    } finally {
        // Best-effort cleanup; whisper writes a few sibling files.
        await rm(tmpDir!, { recursive: true, force: true }).catch(() => undefined);
    }
};

// ---------------------------------------------------------------------------
// Path B: external Whisper-compatible API
// ---------------------------------------------------------------------------

const transcribeViaApi = async (sourcePath: string): Promise<TranscribeResult> => {
    const url = env.WHISPER_API_URL!;
    log.info("uploading to whisper api", { url, sourcePath });

    // Extract audio first to keep the upload small. 16 kHz mono is plenty.
    const tmpDir = await mkdir(join(tmpdir(), `cassette-whisper-api-${Date.now()}`), { recursive: true });
    const wavPath = join(tmpDir!, "audio.wav");
    try {
        await spawnSilent("ffmpeg", [
            "-y",
            "-i",
            sourcePath,
            "-ar",
            "16000",
            "-ac",
            "1",
            "-c:a",
            "pcm_s16le",
            "-vn",
            wavPath,
        ]);

        const buf = await readFile(wavPath);
        const fd = new FormData();
        fd.append("file", new Blob([buf as BlobPart], { type: "audio/wav" }), "audio.wav");
        fd.append("model", "whisper-1");
        fd.append("response_format", "vtt");

        const headers: Record<string, string> = {};
        if (env.WHISPER_API_KEY) headers["Authorization"] = `Bearer ${env.WHISPER_API_KEY}`;

        const res = await fetch(url, { method: "POST", headers, body: fd });
        if (!res.ok) {
            const body = await res.text().catch(() => "");
            throw new Error(`whisper api ${res.status}: ${body.slice(0, 500)}`);
        }
        const vtt = await res.text();
        return { vtt, detectedLang: inferLangFromVtt(vtt) ?? "en" };
    } finally {
        await rm(tmpDir!, { recursive: true, force: true }).catch(() => undefined);
    }
};

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export const transcribe = async (sourcePath: string): Promise<TranscribeResult> => {
    if (env.WHISPER_BINARY_PATH && env.WHISPER_MODEL_PATH) {
        return transcribeViaBinary(sourcePath);
    }
    if (env.WHISPER_API_URL) {
        return transcribeViaApi(sourcePath);
    }
    throw new Error("Whisper is not configured. Set WHISPER_BINARY_PATH+WHISPER_MODEL_PATH or WHISPER_API_URL.");
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const spawnSilent = (cmd: string, args: string[]): Promise<void> =>
    new Promise((resolve, reject) => {
        const child = spawn(cmd, args, { stdio: ["ignore", "ignore", "pipe"] });
        let stderr = "";
        child.stderr?.on("data", (chunk: Buffer) => {
            stderr += chunk.toString("utf8");
        });
        child.on("error", reject);
        child.on("close", (code) => {
            if (code === 0) resolve();
            else reject(new Error(`${cmd} exited with code ${code}: ${stderr.slice(-1024)}`));
        });
    });

const inferLangFromVtt = (vtt: string): string | null => {
    // whisper.cpp emits a `# language: en` line in some builds; otherwise
    // there is no language metadata in the VTT. Default to "en" in that case.
    const m = /^#\s*language\s*:\s*([a-z]{2,3})\b/im.exec(vtt);
    return m?.[1] ?? null;
};

const navigatorHardwareConcurrency = (): number => {
    // Cheap CPU-count probe for the threads flag.
    try {
        return Number(process.env["WHISPER_THREADS"] ?? 4);
    } catch {
        return 4;
    }
};

// Suppress the unused-execFile import in some build modes.
void execFileAsync;
